### ISSUE TITLE
CLI parsers

### ISSUE THREAD

**Issue by henryiii** [r-lyeh/single_file_libs#116]
I'd like to see a new section with command line interface (CLI) parsers; I'm the primary author of CLI11, which has a single file release (similar to the way Catch/Catch2 works). I know of a few other CLI single file projects, as well. Would you be interested in a PR that adds CLI11 and whatever else I can dig up?

**Comment by nothings** [comment]
There is such a section already: https://github.com/nothings/single_file_libs#argv

Feel free to submit your lib though.

**Comment by henryiii** [comment]
Okay, thanks! I somehow missed that section. I'm glad I asked. I'll make a submission soon.
