### ISSUE TITLE
mini-yaml is not a header-only library

### ISSUE THREAD

**Issue by paleozogt** [r-lyeh/single_file_libs#156]
While [mini-yaml](https://github.com/jimmiebergmann/mini-yaml) has a single _interface_ header, it requires compiling/linking to an implementation .cpp file.

See mini-yaml issue [here](https://github.com/jimmiebergmann/mini-yaml/issues/1#issuecomment-495385642).

**Comment by nothings** [comment]
The listing on single-file-libs explicitly says it's two files, not one, so there's no meaningful bug here.

**Comment by paleozogt** [comment]
The problem isn't that there's two files, or even that you have to include a .cpp file (which is weird enough).  The problem is that you can't include the .cpp file more than once.

Consider these two modules of in the same project:

```
// foo.cpp
#include "yaml/Yaml.hpp"
#include "yaml/Yaml.cpp"
...
```

and

```
// bar.cpp
#include "yaml/Yaml.hpp"
#include "yaml/Yaml.cpp"
...
```

This will lead to multiply-defined symbols.  This doesn't seem like a header-only library to me.

**Comment by HSchmale16** [comment]
Nobody in their right mind should be including a .cpp file into another
.cpp file. Just add the mini-yaml.cpp to your srcs in your makefile.

**Comment by paleozogt** [comment]
Exactly.  But isn't adding a .cpp file into your project the exact kind of integration complexity that single-file header libraries are trying to avoid?

**Comment by nothings** [comment]
Any entry in single-file-libs with > 1 in the 'files' column is generally not a header-file-only library. If you only want header-file-libraries only, avoid any entry with > 1 in the files column. This is discussed in the FAQ at the bottom of the list, and just above the FAQ.

**Comment by HSchmale16** [comment]
I would say it has more to do with avoiding the complexity of dynamic
linking and keeping all your code in one place. It's not really complex to
add one file to your sources list. It's much more difficult to track down a
specific version of a dll or a rare library for compiling ancient software.

**Comment by paleozogt** [comment]
I guess I misunderstood this list to be #include-only libraries, even if there were more than one file to #include.

Sorry for the trouble.

**Comment by jimmiebergmann** [comment]
> 
> ..., even if there were more than one file to #include.
> 

No, you'll need to include one file, yaml.hpp, but you'll also need to compile yaml.cpp.
