### ISSUE TITLE
possible candidate: visit_struct

### ISSUE THREAD

**Issue by cbeck88** [r-lyeh/single_file_libs#18]
I have a library here called `visit_struct` which might fit with your criteria:

https://github.com/cbeck88/visit_struct

There are technically several files here, not just one, however, the main file `visit_struct.hpp` can be used as a stand-alone and gets you the vast majority of the functionality. I think this is how most are using it. The extra headers are for extra features / compatibility with other libraries.

The main header is also quite short and the library as a whole is minimalistic, I think it fits well with the premise here.

Cheers

**Comment by nothings** [comment]
Added.
