### ISSUE TITLE
Dead Link (HappyHTTP)

### ISSUE THREAD

**Issue by ghost** [r-lyeh/single_file_libs#191]
It appears as though the github repository for the happyHTTP library no longer exists or has been changed to private. It might be good to remove it from the list. If it's preferable I can just create a PR to remove it myself, but I wanted to be sure I wasn't missing something first.

https://github.com/Zintinio/HappyHTTP

**Comment by elijahfhopp** [comment]
https://github.com/mingodad/HappyHTTP
and
http://scumways.com/happyhttp/happyhttp.html

are both working links.
