### ISSUE TITLE
Add Prof: self-contained C/C++ profiler library for Linux

### ISSUE THREAD

**Issue by cyrus-and** [r-lyeh/single_file_libs#24]
Maybe [Prof][1] could fit this list. It's Linux-only though.

- Self-contained C/C++ profiler library for Linux
- [prof.h](https://github.com/cyrus-and/prof/blob/master/prof.h)
- MIT (included)

[1]: https://github.com/cyrus-and/prof
[2]: https://github.com/cyrus-and/prof/blob/master/prof.h

**Comment by nothings** [comment]
added
