### ISSUE TITLE
generators/corroutines for C++

### ISSUE THREAD

**Issue by c-smile** [r-lyeh/single_file_libs#26]
https://github.com/c-smile/cpp-generators
But it just one .hpp file, not two. Will it qualify?

**Comment by nothings** [comment]
One file is fine (it is "single-file" libs).

But not being able to $yield inside switch, and not being able to push $yield into another called function (I assume, the documentation isn't explicit about this) makes it all seem a bit like an incomplete solution, not something that really solves the problem. (Maybe this is the best you can do in C++ natively, but I'm not sure that's worth it.)

**Comment by c-smile** [comment]
Yes, there are limitations but in most cases when you need exactly generators it works perfectly - lightweight and simple.

**Comment by nothings** [comment]
added
