### ISSUE TITLE
Single File Operating System

### ISSUE THREAD

**Issue by oosmos** [r-lyeh/single_file_libs#28]
Perhaps my single-file operating system, OOSMOS, can be included in your list.

[oosmos.com website ](http://oosmos.com )
[OOSMOS on GitHub](https://github.com/oosmos/oosmos) 

Cheers

**Comment by nothings** [comment]
It's neat, but it seems more like a framework than a library?

**Comment by oosmos** [comment]
Hi Sean,

It can be viewed as both.  If you define framework as 'inversion of control', then I'd say that `OOSMOS` is not a pure framework because the user is in complete control.  They still "own" `main()` and control when the state machine objects are visited via the `oosmos_RunStateMachines()` API.  If you define framework as a library that does callbacks, then, yes, it does callbacks.  I noticed the inclusion of `mm_sched.h` for multitasking, which makes use of callbacks in a similar fashion.

It's a nice list with a theme that I very much appreciate.  I'd be honored to be included but I realize that you have to draw the line somewhere.

Mark Glenn

**Comment by nothings** [comment]
added
