### ISSUE TITLE
miniexpect

### ISSUE THREAD

**Issue by rwmjones** [r-lyeh/single_file_libs#38]
miniexpect is an expect-like library for C written as two files, a source file and a header file, so I believe it fits the definition.  It has a single dependency (PCRE) but that is very widely available, even on Android.  I have compiled this on many different Linux architectures, but to be fair never on Windows, although I don't have a reason to believe it would not work on Windows.

Source: http://git.annexia.org/?p=miniexpect.git;a=tree (only miniexpect.c and miniexpect.h are required, the other files are documentation, tests and examples).

More about it: https://rwmj.wordpress.com/2014/04/25/miniexpect-a-small-expect-library-for-c/

**Comment by nothings** [comment]
I think I have to pass on it because of the dependency on PCRE, since PCRE is *not* a single-file library.
