### ISSUE TITLE
Simple, compact, endian-safe and header-only serialization/deserialization for C++

### ISSUE THREAD

**Issue by voidah** [r-lyeh/single_file_libs#40]
https://github.com/voidah/archive

license: public domain
The only required file is archive.h
Usage examples in main.cpp

**Comment by voidah** [comment]
Features:

Serialize to/from any c++ standard stream (fstream, sstream, ...)
Endian-safe
Compact binary serialization
Header-only
No library dependencies
POD, arrays and stl containers supported out of the box
Easy to serialize user defined objects

**Comment by r-lyeh-archived** [comment]
Very cool and small. It's missing a LICENSE file / legal text somewhere, though :)

**Comment by voidah** [comment]
Thx for the comment, fixed the missing license (it now state clearly it's public domain in the top of archive.h)

**Comment by nothings** [comment]
added

**Comment by earonesty** [comment]
Similar lib, but more like protobuf, in that there's an extensible schema and a wire format: https://github.com/earonesty/qserial
