### ISSUE TITLE
BTAC1C: Extended ADPCM Mini Encoder/Decoder

### ISSUE THREAD

**Issue by cr88192** [r-lyeh/single_file_libs#41]
mentioned on Twitter, but trying here, if there is something special about this:
https://github.com/cr88192/bgbtech_misc/blob/master/mini/btac1c_mini0.h

a basic format spec:
https://github.com/cr88192/bgbtech_misc/wiki/BTAC1C

what is it:
a variant of MS-IMA-ADPCM, with some stuff to fudge blocks to power-of-2 sizes, and some extended filters (intended to hopefully allow for higher audio quality vs raw ADPCM);
has a compatible subset with the normal MS-IMA-ADPCM (mono audio can be decoded, and encoder can be forced to produce normal ADPCM).

what is it intended for:
mostly for allowing arbitrary blocks to be decoded in arbitrary order, such as in the back-end of a mixer;
this avoids the cost (and memory use) of up-front decoding into PCM, while IME generally fast enough to not add a significant overhead over the use of raw PCM audio, with a bitrate not significantly worse than typical MP3 audio (given ~ 4 bits/sample, 22kHz gives 88kbps, and 11kHz gives 44kbps).

what does this not address:
it doesn't directly address either WAV loading, or managing a sample-block cache, as this would add a fair bit of code (and a simplistic WAV loader which spits out PCM would completely miss the point).

approx measured speeds (on a 3 GHz AMD K10, MSVC /O2):
  stereo: encode= ~ 3 megasamples/second, decode=~ 42 megasamples/second 
  mono: encode= ~ 10 megasamples/second, decode=~ 63 megasamples/second

license: MIT.

side notes:
elsewhere I also have a Windows ACM implementation (decodes this variant, but only encodes an older/simpler subset for now);
this is derived mostly from code copy/pasted from my 3D engine.

**Comment by nothings** [comment]
I've linked to the source code page, but people going there aren't going to see the above info or the format spec, so you might want to put pointers to them or reorganize.
