### ISSUE TITLE
Linkom: single header command line parser 

### ISSUE THREAD

**Issue by hernandp** [r-lyeh/single_file_libs#43]
This is my own library, it's primarily targeted at Windows programmers. Includes an optional COM bindings to use it in other languages.

https://github.com/hernandp/linkom

**Comment by hernandp** [comment]
Sorry , I did not see that multiplatform was required -- will port to Unix/Linux.

**Comment by nothings** [comment]
You don't have to have actually compiled it on other platforms yourself, just avoid using features that make it non-portable so it _probably_ works on other platforms (and are willing to fix things that prevent it from working on other platforms).

And something like _Optional_ COM bindings for one platform is fine.

**Comment by hernandp** [comment]
Fine, i'll fix it (due to non-portable "safe" string functions from Microsoft) and ask for inclusion on the list. By the way, the port to Linux is a healthy thing that was projected, so thanks for the "strict" requirements ;)

**Comment by hernandp** [comment]
Also, it's C-based and the COM bindings are of course, optional.

**Comment by hernandp** [comment]
Thanks for your attention.  Now successfully builds and passes tests under Linux GCC / Clang. A nice exercise.  
Thanks!   API Interface is C / C++.   For Windows systems, there are optional COM bindings, as stated in the README file.
https://github.com/hernandp/linkom

**Comment by nothings** [comment]
added
