### ISSUE TITLE
add ennorehling/clibs/selist.[hc]

### ISSUE THREAD

**Issue by ennorehling** [r-lyeh/single_file_libs#50]
From my own collection of single-file libraries, I would like to submit selist.[hc], which implement a space-efficient list by way of an unrolled linked list, by bunching up several nodes into one, reducing both memory overhead for pointers and required number of allocations.

My repository is here: https://github.com/ennorehling/clibs and it contains more than those two files, but I don't feel the rest of the code is ready for submission (yet).

**Comment by saucecode** [comment]
Merry new year from the Philippines.

**Comment by nothings** [comment]
Just to be clear, it appear you put the ISC license text in those files, while there's an Apache LICENSE file in the directory which presumably isn't meant to apply to them in isolation. Anyway, added and closing, only reply if I misunderstood the licensing intent.
