### ISSUE TITLE
AVL tree implementation

### ISSUE THREAD

**Issue by etherealvisage** [r-lyeh/single_file_libs#51]
Hi,

I have a [public-domain AVL tree implementation in pure C89](https://github.com/etherealvisage/avl) that works well on embedded devices and in general applications as well. You can ignore the LICENSE file in the repository, as it's simply a public-domain placeholder. See src/avl.[ch] for the actual library code.

I have several other libraries that I will clean up and submit issues for as well, time permitting.

- ethereal

**Comment by nothings** [comment]
added
