### ISSUE TITLE
TinySoundFont, a SoundFont2 synthesizer library

### ISSUE THREAD

**Issue by schellingb** [r-lyeh/single_file_libs#52]
Hi

I'd like to request an addition for [TinySoundFont](https://github.com/schellingb/TinySoundFont), a portable software synthesizer using SoundFont2 sound bank files.
It's a single-file library closely following the [stb_howto.txt](https://github.com/nothings/stb/blob/master/docs/stb_howto.txt).

| category | library                                                               | license              | API |files| description
| ---------| --------------------------------------------------------------------- |:--------------------:|:---:|:---:| -----------
| audio    |  [TinySoundFont](https://github.com/schellingb/TinySoundFont)                | MIT                  |C/C++|**1**| SoundFont2 synthesizer

Thanks for the list and the libs!

**Comment by nothings** [comment]
added. thanks for supplying all the info in table form!
