### ISSUE TITLE
Adding my library (for CLI interfaces)

### ISSUE THREAD

**Issue by ronen25** [r-lyeh/single_file_libs#80]
Hi,

I created a small library for writing command-line interfaces, kindda like the cmd module in Python.
It's located here:
http://github.com/ronen25/libcmdf

It's single-header, ANSI C, Public Domain.

Wondering if it can be included here.
Thank you, and thanks for this incredible collection!

**Comment by ronen25** [comment]
Hi, does the library meet all integration criteria?
If not then I'll be more than happy to bring it up to standard.

Thanks!

**Comment by nothings** [comment]
I believe it does, I just don't update the list from 'Issues' as often as I do from 'Pull requests', so it's been quite a while.

**Comment by ronen25** [comment]
Sure thing, no problem! I've opened a pull request for this.

**Comment by nothings** [comment]
Closing this now so I don't have to remember to close it when I do the PR.
