### ISSUE TITLE
Add simple-svg library.

### ISSUE THREAD

**Issue by justinjk007** [r-lyeh/single_file_libs#83]
https://github.com/adishavit/simple-svg

This library generates svg images for vectors, all from a small single header file

**Comment by nothings** [comment]
Any particular reason you're closing this?

**Comment by justinjk007** [comment]
I like to close threads if it's unresolved after a long time.

On Jan 21, 2018 12:20 AM, "Sean Barrett" <notifications@github.com> wrote:

Any particular reason you're closing this?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/nothings/single_file_libs/issues/83#issuecomment-359224858>,
or mute the thread
